In [1]:
import torch

In [2]:
A=torch.tensor ([[4.,0.,5.],[-1., 3.,2.]]) 
B=torch.tensor ([[1., 1.,1.],[3., 5.,7.]]) 
C=torch.tensor ([[2., -3.,], [0,1]])

In [3]:
A+B

tensor([[5., 1., 6.],
        [2., 8., 9.]])

In [4]:
C@A

tensor([[11., -9.,  4.],
        [-1.,  3.,  2.]])

In [5]:
torch.sigmoid(A)

tensor([[0.9820, 0.5000, 0.9933],
        [0.2689, 0.9526, 0.8808]])

In [6]:
import pandas as pd 

In [7]:
x = torch.tensor([[1., 1.], [1.,2.],[1. , 3.],[1.,4.]])
y = torch.tensor([2.,3.,3.,5.])


In [8]:
from torch.linalg import inv
w = inv(x.T @ x) @ x.T @ y
w

tensor([1.0000, 0.9000])

In [9]:
x2 = torch.tensor([[1., 1., 1.], [1.,2.,3.],[1., 3. , 4.],[1., 4.,3.]])
y2 = torch.tensor([1.,3.,4.,5.])

In [11]:

w2 = inv(x2.T @ x2) @ x2.T @ y2 

In [12]:
x3 = torch.tensor([[1., 1., 1.], [1.,2., 4.],[1. , 3., 9],[1.,4.,16.]])
y3 = torch.tensor([2.,3.,3.,5.])

In [13]:
w3 = inv(x3.T @ x3) @ x3.T @ y3 

In [14]:
w3

tensor([ 2.2500, -0.3500,  0.2500])

In [15]:
from sklearn.metrics import mean_squared_error as mse
mse(y3, x3 @ w3)

0.112500004

In [16]:
mse(y2, x2 @ w2)

0.02173914

In [17]:
import torch.nn as nn

In [18]:
def gini(x):
    total = 0
    for i, xi in enumerate(x[:-1], 1):
        total += np.sum(np.abs(xi - x[i:]))
    return total / (len(x)**2 * np.mean(x))